version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9004:9004'
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm run dev && npm start"
